it('Alpha login', () => {
    
    cy.visit('https://beta.api.trukkr.pk')
    cy.viewport(1280, 720)
    cy.get('#userName').type('devacc@trukkr.pk')
    cy.get('#password').type('123456789')
    cy.get('#mui-1').click()
    cy.get(':nth-child(4) > .c-sidebar-nav-link').click()
    cy.get('#mui-13').click()
    cy.get(':nth-child(1) > .MuiTypography-root > .row > .col-12 > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > #client-dropdown').click()
    cy.get('#client-dropdown-option-30', { timeout: 5000 }).click({ force: true })
    cy.get(':nth-child(2) > .MuiTypography-root > .row > .col-12 > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > #client-dropdown').click()
    cy.get('#client-dropdown-option-30', { timeout: 5000 }).click({ force: true })
    cy.get('.form-group > .MuiFormControl-root > .MuiOutlinedInput-root').click()
    cy.get(':nth-child(4) > :nth-child(7) > .MuiButtonBase-root').click({ force: true })
    cy.get('.time-slot > .css-n7p1v0-control > .css-1hwfws3').click()
    cy.get('#react-select-2-option-4').click()
    cy.get('#mui-17').click()
    cy.wait(5000)
    cy.get(':nth-child(1) > :nth-child(1) > .css-2b097c-container > .css-n7p1v0-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click({ force: true })
    cy.get('#react-select-4-option-3').click({ force: true })
    cy.get('input[name="weight.weight"]').type('12')
    cy.get('.css-jvev8-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click({force: true })
    // cy.wait(3000)
    cy.get('#react-select-5-option-2').click({force: true }) 
    cy.get('input[name="weight.quantity"]').type('45')
    cy.get('#containerNumber').type('ab123')
    cy.get(':nth-child(4) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiAutocomplete-endAdornment > .MuiButtonBase-root > [data-testid="ArrowDropDownIcon"]').click()
    cy.get('#asynchronous-demo-option-1',{timeout:500}).click()
    cy.get('#mui-26').click()
    cy.get('#mui-19').click()
    cy.wait(2000)
    cy.get('#categoryName > .css-n7p1v0-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click()
    cy.get('#react-select-6-option-2').click()
    cy.get('#vehicleType > .css-n7p1v0-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click()
    cy.get('#react-select-7-option-1').click()
    // cy.get('#vehicleRequestedQty').type(2)
    cy.get('#mui-31').click()
    cy.get('h5 > .float-right').click()
    cy.get('#temperature').type(30)
    cy.get('.MuiButtonBase-root > [data-testid="ArrowDropDownIcon"]').click()
    cy.get('#asynchronous-demo-option-2').click()
    cy.get('#preferredPayment > .css-n7p1v0-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click()
    cy.get('#react-select-3-option-1').click()
    cy.get('.mb-3 > :nth-child(1) > .row > :nth-child(2) > .MuiButton-root').click()
    cy.wait(3000)
    cy.get('#fileName').type('Cypress Test')
    cy.get('.mb-0.col-12 > .css-2b097c-container > .css-n7p1v0-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click()
    cy.get('#react-select-8-option-2').click()
    cy.get('#description').type('Cypress testing on request page!!!')
    cy.get('[type="file"]').attachFile('image.png', { allowEmpty: true })
    cy.wait(2000)
    cy.get('#mui-36').click({force:true})
    cy.get('#doNUmber').type('12345678')
    cy.get('.MuiBox-root > .row > .col-12 > .form-control').type('anything!!!')
    cy.get('#mui-24').click()
    cy.get('#mui-24').click()
    cy.get(':nth-child(1) > :nth-child(8) > .hover-link > span').click()
    



})
