it('Alpha login', () => {
    cy.visit('https://beta.api.trukkr.pk')
    cy.get('#userName').type('zohaib.naqvi@artisticmilliners.com')
    cy.get('#password').type('123456789')
    cy.get('#mui-1').click()
    cy.get(':nth-child(4) > .c-sidebar-nav-link').click()
    cy.get('#mui-2', { timeout: 5000 }).click({ force: true })

    cy.get(':nth-child(1) > .MuiTypography-root > .row > .col-12 > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > #client-dropdown').click()
    cy.get('#client-dropdown-option-1', { timeout: 5000 }).click({ force: true })
    cy.get(':nth-child(2) > .MuiTypography-root > .row > .col-12 > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > #client-dropdown').click()
    cy.get('#client-dropdown-option-2', { timeout: 5000 }).click({ force: true })
    cy.get('#mui-6').click()
    cy.get(':nth-child(4) > :nth-child(6) > .MuiButtonBase-root').click({ force: true })
    cy.get('#mui-7').click()
    cy.get('.css-1umqo6f').click()
    // cy.get('.MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv').click()
    cy.get('[name="request"] > :nth-child(3) > :nth-child(2) > .MuiButton-root', { timeout: 5000 }).click({ force: true })
    cy.get('#categoryName > .css-o2ohsi-control > .css-1hwfws3', { timeout: 5000 }).click({ force: true })
    cy.get('#categoryName > .css-o2ohsi-control > .css-1hwfws3').click()
    // cy.get('#categoryName > .css-o2ohsi-control > .css-1hwfws3-option-3').click()
    // cy.get('.css-1uccc91-singleValue').click()
    // cy.get('.css-1g6gooi',{timeout:500}).click({force:true})
    // cy.get('#categoryName > .css-o2ohsi-control > .cyss-1wy0on6 > .css-tlfecz-indicatorContainer > .css-19bqh2r', { timeout: 5000 }).click({ force: true })
    cy.get('#react-select-3-option-1', { timeout: 500 }).click({ force: true })
    cy.get('#vehicleType > .css-o2ohsi-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer > .css-19bqh2r > path', { timeout: 500 }).click({ force: true })
    cy.get('#react-select-4-option-0', { timeout: 500 }).click({ force: true })
    cy.get('#vehicleRequestedQty').type('3')
    cy.get('#mui-10',{timeout:500}).click({force:true})
    cy.get(':nth-child(5) > :nth-child(2) > .MuiButton-root').click()
    cy.get('.modal-body > :nth-child(1) > :nth-child(1) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiAutocomplete-endAdornment > .MuiButtonBase-root > [data-testid="ArrowDropDownIcon"] > path').click()
    cy.get('#asynchronous-demo-option-3',{timeout:500}).click({force : true})
    cy.get('input[name="weight.weight"]').type('12')
    cy.get('.css-19bqh2r').click({multiple :true,force: true})
    // cy.get('.css-19bqh2r',{timeout:500}).click({ multiple: true ,force: true})
    cy.get('#react-select-5-option-2').click({force: true }) 
    // cy.get('.css-o2ohsi-control',{timeout :600}).click({multiple: true,force:true})
    // cy.get('.css-19bqh2r',{timeout:500}).click({force: true})
    // cy.get('#react-select-5-option-2').click({ multiple: true, force: true })
    cy.get('#containerNumber').type('ab123')
    cy.get(':nth-child(4) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiAutocomplete-endAdornment > .MuiButtonBase-root > [data-testid="ArrowDropDownIcon"]').click()
    cy.get('#asynchronous-demo-option-1',{timeout:500}).click()
    cy.get('#mui-12').click()
    cy.get('#temperature').type('34')
    cy.get('#asynchronous-demo').click()
    cy.get("#asynchronous-demo-option-2").click({force:true})
    cy.get('.css-1hwfws3').click()
    cy.get('#react-select-2-option-2').click()
    cy.get('.mt-4 > .col-1 > .MuiCheckbox-root > .PrivateSwitchBase-input').click()
    cy.get('#mui-8').click()
    cy.get(':nth-child(1) > div > .card-title').click()
    cy.get('[value="6hour"] > .form-check-label').click()
    cy.get('#mui-3').click()
    cy.get(':nth-child(4) > :nth-child(4) > .MuiButtonBase-root').click({waitForAnimations: false})
    cy.get(':nth-child(1) > .modal > .modal-dialog > .modal-content > .modal-body').click()
})
// })