it('Alpha login', () => {
    cy.visit('https://beta.api.trukkr.pk')
    cy.get('#userName').type('zohaib.naqvi@artisticmilliners.com')
    cy.get('#password').type('123456789')
    cy.get('#mui-1').click()
    cy.get(':nth-child(4) > .c-sidebar-nav-link').click()
    cy.get('#mui-2', { timeout: 5000 }).click({ force: true })

    cy.get(':nth-child(1) > .MuiTypography-root > .row > .col-12 > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > #client-dropdown').click()
    cy.get('#client-dropdown-option-1', { timeout: 5000 }).click({ force: true })
    cy.get(':nth-child(2) > .MuiTypography-root > .row > .col-12 > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > #client-dropdown').click()
    cy.get('#client-dropdown-option-2', { timeout: 5000 }).click({ force: true })
    cy.get('#mui-6').click()
    cy.get(':nth-child(4) > :nth-child(6) > .MuiButtonBase-root').click({ force: true })
    cy.get('#mui-7').click()
    cy.get('.css-1umqo6f').click()
    // cy.get('.MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv').click()
    cy.get('[name="request"] > :nth-child(3) > :nth-child(2) > .MuiButton-root', { timeout: 5000 }).click({ force: true })
    cy.get('#categoryName > .css-o2ohsi-control > .css-1hwfws3', { timeout: 5000 }).click({ force: true })
    cy.get('#categoryName > .css-o2ohsi-control > .css-1hwfws3').click()
    // cy.get('#categoryName > .css-o2ohsi-control > .css-1hwfws3-option-3').click()
    // cy.get('.css-1uccc91-singleValue').click()
    // cy.get('.css-1g6gooi',{timeout:500}).click({force:true})
    // cy.get('#categoryName > .css-o2ohsi-control > .cyss-1wy0on6 > .css-tlfecz-indicatorContainer > .css-19bqh2r', { timeout: 5000 }).click({ force: true })
    cy.get('#react-select-3-option-1', { timeout: 500 }).click({ force: true })
    cy.get('#vehicleType > .css-o2ohsi-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer > .css-19bqh2r > path', { timeout: 500 }).click({ force: true })
    cy.get('#react-select-4-option-0', { timeout: 500 }).click({ force: true })
    cy.get('#vehicleRequestedQty').type('3')
    cy.get('#mui-10',{timeout:500}).click({force:true})
    cy.get(':nth-child(5) > :nth-child(2) > .MuiButton-root').click()
    cy.get('.modal-body > :nth-child(1) > :nth-child(1) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiAutocomplete-endAdornment > .MuiButtonBase-root > [data-testid="ArrowDropDownIcon"] > path').click()
    // cy.get('.MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-b52kj1').click()
    cy.get('#asynchronous-demo-option-3',{timeout:500}).click({force : true})
    // cy.get('#weight\.weight').type('6',{force :true})
    // cy.get('#weight\.unit > .css-o2ohsi-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer > .css-19bqh2r > path').click()
    // cy.get('#weight\.quantity').type('6')
    cy.get('#containerNumber').type('ab123')
    cy.get(':nth-child(4) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiAutocomplete-endAdornment > .MuiButtonBase-root > [data-testid="ArrowDropDownIcon"]').click()
})
// })